name: note_sqflite_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.2
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  rxdart: ^0.27.7
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
