name: notes_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  fast_immutable_collections: ^10.2.2
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  note_sqflite_api:
    path: ../note_sqflite_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
