name: local_sqflite_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
dependencies:
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.2
  fpdart: ^1.1.0
  rxdart: ^0.27.7
  sqflite: ^2.3.3
